# Generated by Django 5.2.1 on 2025-05-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('model', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stock', models.IntegerField()),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('Category', models.CharField(choices=[('mobile', 'Mobile'), ('clothing', 'Clothing'), ('electronics', 'Electronics')], default='mobile', max_length=20)),
            ],
        ),
    ]
